/**
 * src/providers/payment/PaymentProvider.ts
 *
 * PaymentProvider interface — ADR-003 / ADR-016.
 *
 * All payment operations MUST go through this interface.
 * No route handler, service, or UI component may call a provider SDK directly.
 *
 * Supported concrete implementations:
 *   - StripeProvider    (USD default — src/providers/payment/StripeProvider.ts)
 *   - PayPalProvider    (src/providers/payment/PayPalProvider.ts)
 *   - CashAppProvider   (src/providers/payment/CashAppProvider.ts)
 *   - PaystackProvider  (NGN fallback — src/providers/payment/PaystackProvider.ts)
 */

import type { PaymentProviderName } from "@/types";

// ─── Shared types ─────────────────────────────────────────────────────────────

export interface InitiatePaymentParams {
  /** Amount in integer minor units (cents for USD, kobo for NGN, etc.) */
  amount: number;
  currency: string;
  /** Opaque reference generated by our system; becomes Payment.providerRef */
  reference: string;
  /** Fan-facing description shown on the provider's checkout page */
  description: string;
  /** URL to redirect the customer to after payment */
  callbackUrl: string;
  customerEmail?: string;
  customerName?: string;
  metadata?: Record<string, string>;
}

export interface PaymentIntentResult {
  provider: PaymentProviderName;
  providerRef: string;
  /** Redirect URL (Paystack / PayPal hosted checkout) */
  redirectUrl?: string;
  /** Client secret for Stripe.js Payment Element */
  clientSecret?: string;
  /** PayPal order ID for PayPal JS SDK */
  paypalOrderId?: string;
}

export interface VerifyPaymentResult {
  success: boolean;
  amount: number;    // minor units as returned by provider
  currency: string;
  providerTxId: string;
  raw: unknown;      // raw provider response, stored as providerMeta for audit
}

export interface RefundParams {
  providerRef: string;
  /** Amount to refund in minor units; omit for full refund */
  amount?: number;
  reason?: string;
}

export interface RefundResult {
  success: boolean;
  providerRefundId: string;
  raw: unknown;
}

export interface WebhookVerifyResult {
  isValid: boolean;
  eventId: string;
  eventType: string;
  providerRef: string;
  amount: number;
  currency: string;
  raw: unknown;
}

// ─── Interface ────────────────────────────────────────────────────────────────

export interface PaymentProvider {
  /** Unique identifier for this provider */
  readonly name: PaymentProviderName;

  /**
   * Initiate a payment session.
   * Returns a redirect URL (hosted checkout) or a client secret (SDK checkout).
   */
  initiatePayment(params: InitiatePaymentParams): Promise<PaymentIntentResult>;

  /**
   * Server-side verify that a transaction completed successfully.
   * Called on webhook receipt AND on customer return to thank-you page.
   * NEVER trust the result of the client-side redirect alone — always call this.
   */
  verifyPayment(providerRef: string): Promise<VerifyPaymentResult>;

  /**
   * Verify an inbound webhook signature and extract normalised event data.
   * Returns { isValid: false } if signature is wrong — caller must return 400.
   */
  verifyWebhook(
    rawBody: string | Buffer,
    signature: string
  ): Promise<WebhookVerifyResult>;

  /**
   * Issue a refund. Super Admin only (enforced at the route level).
   */
  refund(params: RefundParams): Promise<RefundResult>;
}
